/**
 * @file
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * Standardized error codes for the application
 * These codes provide consistent, machine-readable error identification
 */
export enum ErrorCode {
  // General errors (1000-1999)
  INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER',
  UNKNOWN_ERROR = 'ERR_UNKNOWN',
  BAD_REQUEST = 'ERR_BAD_REQUEST',
  NOT_FOUND = 'ERR_NOT_FOUND',
  METHOD_NOT_ALLOWED = 'ERR_METHOD_NOT_ALLOWED',

  // Validation errors (2000-2999)
  VALIDATION_ERROR = 'ERR_VALIDATION',
  INVALID_INPUT = 'ERR_INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'ERR_MISSING_FIELD',
  INVALID_FORMAT = 'ERR_INVALID_FORMAT',

  // Authentication errors (3000-3999)
  UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  INVALID_CREDENTIALS = 'ERR_INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED',
  TOKEN_INVALID = 'ERR_TOKEN_INVALID',
  TOKEN_MISSING = 'ERR_TOKEN_MISSING',

  // Authorization errors (4000-4999)
  FORBIDDEN = 'ERR_FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'ERR_INSUFFICIENT_PERMISSIONS',
  ACCESS_DENIED = 'ERR_ACCESS_DENIED',

  // Resource errors (5000-5999)
  RESOURCE_NOT_FOUND = 'ERR_RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'ERR_RESOURCE_EXISTS',
  RESOURCE_CONFLICT = 'ERR_RESOURCE_CONFLICT',
  RESOURCE_LOCKED = 'ERR_RESOURCE_LOCKED',

  // Database errors (6000-6999)
  DATABASE_ERROR = 'ERR_DATABASE',
  DUPLICATE_ENTRY = 'ERR_DUPLICATE_ENTRY',
  FOREIGN_KEY_VIOLATION = 'ERR_FOREIGN_KEY',
  UNIQUE_CONSTRAINT_VIOLATION = 'ERR_UNIQUE_CONSTRAINT',
  CONNECTION_ERROR = 'ERR_DB_CONNECTION',

  // Business logic errors (7000-7999)
  BUSINESS_RULE_VIOLATION = 'ERR_BUSINESS_RULE',
  OPERATION_NOT_ALLOWED = 'ERR_OPERATION_NOT_ALLOWED',
  INVALID_STATE = 'ERR_INVALID_STATE',
  PRECONDITION_FAILED = 'ERR_PRECONDITION_FAILED',

  // Rate limiting (8000-8999)
  RATE_LIMIT_EXCEEDED = 'ERR_RATE_LIMIT',
  TOO_MANY_REQUESTS = 'ERR_TOO_MANY_REQUESTS',

  // External service errors (9000-9999)
  EXTERNAL_SERVICE_ERROR = 'ERR_EXTERNAL_SERVICE',
  SERVICE_UNAVAILABLE = 'ERR_SERVICE_UNAVAILABLE',
  TIMEOUT = 'ERR_TIMEOUT',
}
